name: Rebecca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64365008-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0489d8'
    - '#ffffff'
    - '#ceb08e'
    - '#7bdbe1'
    - '#00080e'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
