name: Rebecca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0489d8'
    - '#ffffff'
    - '#ceb08e'
    - '#7bdbe1'
    - '#00080e'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
