name: Rebecca
favicon: null
layout_spectrum: 0.24606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0489d8'
    - '#ffffff'
    - '#ceb08e'
    - '#7bdbe1'
    - '#00080e'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
